-- Dong bo hoa lai Sequence cho cac cot Identity sau khi import data
-- Trong Oracle, khi INSERT cung gia tri ID, sequence se KHONG tu dong tang.
-- Chung ta phai cap nhat lai de sequence tiep tuc tu muc MAX(id) + 1, tranh loi ORA-00001 (Unique constraint)

ALTER TABLE role MODIFY id GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE);
ALTER TABLE customer MODIFY id GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE);
ALTER TABLE branch MODIFY id GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE);
ALTER TABLE account MODIFY id GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE);
ALTER TABLE address_shipping MODIFY id GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE);
ALTER TABLE payment_method MODIFY id GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE);

COMMIT;
BEGIN DBMS_OUTPUT.PUT_LINE('>>> Da cap nhat ID Identity thanh cong!'); END;
/
