
-- ==============================================================================
-- 5. Báº£ng Inventory_Request vĂ  Inventory_Request_Detail
-- ==============================================================================
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE TRASUA.inventory_request (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        branch_id NUMBER NOT NULL,
        created_by NUMBER NOT NULL,
        status VARCHAR2(20) DEFAULT ''PENDING'',
        note NVARCHAR2(500),
        created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
        updated_at TIMESTAMP DEFAULT SYSTIMESTAMP,
        CONSTRAINT fk_inv_req_branch FOREIGN KEY (branch_id) REFERENCES TRASUA.branch(id)
    )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE TRASUA.inventory_request_detail (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        request_id NUMBER NOT NULL,
        product_detail_id NUMBER NOT NULL,
        requested_quantity NUMBER DEFAULT 0,
        approved_quantity NUMBER DEFAULT 0,
        CONSTRAINT fk_inv_reqd_req FOREIGN KEY (request_id) REFERENCES TRASUA.inventory_request(id),
        CONSTRAINT fk_inv_reqd_pd FOREIGN KEY (product_detail_id) REFERENCES TRASUA.product_detail(id)
    )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/

-- Ăp dá»¥ng OLS cho inventory_request
BEGIN
    BEGIN
        SA_POLICY_ADMIN.REMOVE_TABLE_POLICY('BRANCH_OLS_POLICY', 'TRASUA', 'inventory_request');
    EXCEPTION WHEN OTHERS THEN NULL; END;
    
    SA_POLICY_ADMIN.APPLY_TABLE_POLICY(
        policy_name    => 'BRANCH_OLS_POLICY',
        schema_name    => 'TRASUA',
        table_name     => 'inventory_request',
        table_options  => 'READ_CONTROL,WRITE_CONTROL,CHECK_CONTROL'
    );
END;
/

-- Táº¡o Trigger tá»± Ä‘á»™ng gáº¯n nhĂ£n OLS cho báº£ng inventory_request khi INSERT
CREATE OR REPLACE TRIGGER TRASUA.trg_ols_inventory_request
BEFORE INSERT ON TRASUA.inventory_request
FOR EACH ROW
BEGIN
    :NEW.label := CHAR_TO_LABEL('BRANCH_OLS_POLICY', 'CONFIDENTIAL:CN' || :NEW.branch_id);
END;
/
